cookie:
  expiry_days: 62
  key: xY&Q*Rcj9Y_HLy2V
  name: Streamlit_login_cookie
credentials:
  usernames:
    Novo:
      email: emil.hansen62@cleancluster.dk
      name: Novo Nordisk Fonden
      password: $2b$12$HKcSNq.cjwVkN0uLZtL62.ZyJqmXqcjQKxYsSLfDTFd.5SBRrS6C2
preauthorized:
  emails:
  - emil.hansen62@cleancluster.dk
