cookie:
  expiry_days: 62
  key: xY&Q*Rcj9Y_HLy2V
  name: Streamlit_login_cookie
credentials:
  usernames:
    admin@cleancluster.dk:
      email: admin@cleancluster.dk
      name: Emil
      password: $2b$12$xC3.Np6P0AHbXfJfoqcNbu4E0J4C7CtTyjfd0IvFTRZh0fuzvWkM.
preauthorized:
  emails:
  - admin@cleancluster.dk
