cookie:
  expiry_days: 62
  key: xY&Q*Rcj9Y_HLy2V
  name: Streamlit_login_cookie
credentials:
  usernames:
    admin@cleancluster.dk:
      email: admin@cleancluster.dk
      name: Emil
      password: $2b$12$HKcSNq.cjwVkN0uLZtL62.ZyJqmXqcjQKxYsSLfDTFd.5SBRrS6C2
preauthorized:
  emails:
  - admin@cleancluster.dk
