cookie:
  expiry_days: 62
  key: xY&Q*Rcj9Y_HLy2V
  name: Streamlit_login_cookie
credentials:
  usernames:
    admin@cleancluster.dk:
      email: admin@cleancluster.dk
      name: Emil
      password: $2b$12$lF5jZZ/H1euashebQQUzfuyG7lGMKyLfEC8dkT83RKPVlDIZMGCNO
preauthorized:
  emails:
  - admin@cleancluster.dk
